name: Testing Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Chekout Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11.0.8
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.x
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install transformers==4.11.3
#          pip install tokenizers
#          pip install keybert==0.6.0

      - name: Run Android Linter
        run: ./gradlew :sphinx:application:sphinx:lintDebug

      - name: Run Unit Tests
        run: ./gradlew :sphinx:application:sphinx:testDebugUnitTest

      - name: Assemble Debug APK
        run: ./gradlew :sphinx:application:sphinx:assembleDebug

      - name: Assemble Debug Test APK
        run: ./gradlew :sphinx:application:sphinx:assembleDebugAndroidTest
